import { readFileSync, writeFileSync } from 'node:fs';
import { parseShelleyAddress } from '../src/address';
import { type AuthorizationFields, type AuthorizationRecord, encodeAuthorization, fieldsFromRecord, signAuthorization } from '../src/authorization';
import { bytesToHex } from '../src/bytes';
import { publicKeyFromSecret, signBytes } from '../src/ed25519';
import { blake2b256 } from '../src/hash';
import { signProposal } from '../src/proposal';
import { buildAddress } from '../test/helpers/address-builder';
import { ENGINE_TEST_SECRET } from './gen-vectors';

// Emits two Aiken modules from the TypeScript core, so the TS encoder stays the single source of truth:
// - vectors.test.ak: the committed authorization vectors, checked byte for byte in Aiken
// - fixtures.ak: engine-signed authorizations used by the vault validator tests

const AIKEN_LIB = new URL('../../../contracts/cardano/lib/authority/', import.meta.url);
const VECTORS_JSON = new URL('../test/vectors/authorization.json', import.meta.url);
const HEADER = '//// Generated by packages/core/scripts/gen-aiken.ts. Do not edit.';

const hex = (h: string) => `#"${h.toLowerCase()}"`;

function recipientFields(recipient: string): [number, string, number, string] {
  const a = parseShelleyAddress(recipient);
  const pay: [number, string] = [a.payment.tag === 'key' ? 0 : 1, bytesToHex(a.payment.hash)];
  if (!a.stake) return [...pay, 0, ''];
  return [...pay, a.stake.tag === 'key' ? 1 : 2, bytesToHex(a.stake.hash)];
}

function authLiteral(f: AuthorizationFields, indent: string): string {
  const [payTag, payHash, stakeTag, stakeHash] = recipientFields(f.recipient);
  const rows: Array<[string, string]> = [
    ['chain_tag', String(f.chainTag)],
    ['vault_hash', hex(f.vaultHash)],
    ['mandate_ref', hex(f.mandateRef)],
    ['mandate_hash', hex(f.mandateHash)],
    ['mandate_version', String(f.mandateVersion)],
    ['action_hash', hex(f.actionHash)],
    ['action_type', String(f.actionType)],
    ['asset_policy', hex(f.assetPolicy)],
    ['asset_name', hex(f.assetName)],
    ['amount', f.amount.toString()],
    ['recipient_pay_tag', String(payTag)],
    ['recipient_pay_hash', hex(payHash)],
    ['recipient_stake_tag', String(stakeTag)],
    ['recipient_stake_hash', hex(stakeHash)],
    ['nonce', f.nonce.toString()],
    ['valid_until', f.validUntil.toString()],
    ['requires_principal', f.requiresPrincipal ? '1' : '0'],
    ['verification_ref', hex(f.verificationRef ?? '00'.repeat(32))],
  ];
  const body = rows.map(([k, v]) => `${indent}  ${k}: ${v},`).join('\n');
  return `Authorization {\n${body}\n${indent}}`;
}

function snake(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');
}

export function vectorsModule(): string {
  const vectors: Array<{ name: string; record: AuthorizationRecord }> = JSON.parse(readFileSync(VECTORS_JSON, 'utf8'));
  const tests = vectors.map(({ name, record }, i) => {
    const id = `vector_${i + 1}_${snake(name)}`;
    return [
      `test ${id}() {`,
      `  let auth = ${authLiteral(fieldsFromRecord(record), '  ')}`,
      `  let digest = message.digest(auth)`,
      `  and {`,
      `    message.encode(auth) == ${hex(record.message_hex)},`,
      `    digest == ${hex(record.digest_hex)},`,
      `    verify_ed25519_signature(`,
      `      engine_vkey,`,
      `      digest,`,
      `      ${hex(record.signature_hex)},`,
      `    ),`,
      `    !verify_ed25519_signature(`,
      `      engine_vkey,`,
      `      message.digest(Authorization { ..auth, nonce: auth.nonce + 1 }),`,
      `      ${hex(record.signature_hex)},`,
      `    ),`,
      `  }`,
      `}`,
    ].join('\n');
  });
  const engineVkey = vectors[0]?.record.engine_public_key ?? '';
  return [
    HEADER,
    '',
    'use aiken/crypto.{verify_ed25519_signature}',
    'use authority/message',
    'use authority/types.{Authorization}',
    '',
    `const engine_vkey =\n  ${hex(engineVkey)}`,
    '',
    tests.join('\n\n'),
    '',
  ].join('\n');
}

const usdmPolicy = '16a55b2a349361ff88c03788f93e1e966e5d689605d044fef722ddde';
const usdmName = '0014df10745553444d';
const base: AuthorizationFields = {
  chainTag: 0,
  vaultHash: 'aa'.repeat(28),
  mandateRef: 'bb'.repeat(28),
  mandateHash: 'cc'.repeat(32),
  mandateVersion: 3,
  actionHash: 'dd'.repeat(32),
  actionType: 1,
  assetPolicy: usdmPolicy,
  assetName: usdmName,
  amount: 8_420_000n,
  recipient: buildAddress(0x60, new Uint8Array(28).fill(0x11)),
  nonce: 1n,
  validUntil: 1_800_000_000_000n,
  requiresPrincipal: false,
  verificationRef: 'f0'.repeat(32),
};

function signed(f: AuthorizationFields, signature?: string): { fields: AuthorizationFields; signature: string } {
  return { fields: f, signature: signature ?? signAuthorization(f, ENGINE_TEST_SECRET).signature_hex };
}

// Amount 0 cannot pass the TS encoder, so a stolen engine key is modelled by signing patched bytes.
function signedAmountZero(): { fields: AuthorizationFields; signature: string } {
  const message = encodeAuthorization({ ...base, amount: 1n });
  const amountOffset = 22 + 1 + 28 + 28 + 32 + 4 + 32 + 1 + 28 + 1 + usdmName.length / 2;
  message.fill(0, amountOffset, amountOffset + 8);
  const signature = bytesToHex(signBytes(blake2b256(message), ENGINE_TEST_SECRET));
  return { fields: { ...base, amount: 0n }, signature };
}

export function fixtureCases(): Array<[string, { fields: AuthorizationFields; signature: string }]> {
  return [
    ['release_base', signed(base)],
    ['release_at_autonomous', signed({ ...base, amount: 10_000_000n })],
    ['release_above_autonomous', signed({ ...base, amount: 18_000_000n, requiresPrincipal: true })],
    ['release_above_autonomous_unflagged', signed({ ...base, amount: 18_000_000n })],
    ['release_flagged_small', signed({ ...base, amount: 5_000_000n, requiresPrincipal: true })],
    ['release_at_hard_cap', signed({ ...base, amount: 50_000_000n, requiresPrincipal: true })],
    ['release_above_hard_cap', signed({ ...base, amount: 50_000_001n, requiresPrincipal: true })],
    ['release_old_version', signed({ ...base, mandateVersion: 2 })],
    ['release_other_mandate_hash', signed({ ...base, mandateHash: 'cd'.repeat(32) })],
    ['release_other_mandate_ref', signed({ ...base, mandateRef: 'bc'.repeat(28) })],
    ['release_mainnet', signed({ ...base, chainTag: 1, recipient: buildAddress(0x61, new Uint8Array(28).fill(0x11)) })],
    ['release_other_vault', signed({ ...base, vaultHash: 'ab'.repeat(28) })],
    ['release_action_type_2', signed({ ...base, actionType: 2 })],
    ['release_other_asset_name', signed({ ...base, assetName: '745553444d' })],
    ['release_other_asset_policy', signed({ ...base, assetPolicy: 'ef'.repeat(28) })],
    ['release_amount_zero', signedAmountZero()],
    ['release_to_vault', signed({ ...base, recipient: buildAddress(0x70, new Uint8Array(28).fill(0xaa)) })],
    ['release_other_key', signed(base, signAuthorization(base, new Uint8Array(32).fill(9)).signature_hex)],
    ['release_proposal_signature', signed(base, signProposal(base.actionHash, ENGINE_TEST_SECRET))],
  ];
}

export function fixturesModule(): string {
  const consts = fixtureCases().map(([name, { fields, signature }]) =>
    [
      `pub const ${name}: Signed =`,
      `  Signed {`,
      `    auth: ${authLiteral(fields, '    ')},`,
      `    signature: ${hex(signature)},`,
      `  }`,
    ].join('\n'),
  );
  return [
    HEADER,
    '',
    'use authority/types.{Authorization}',
    '',
    'pub type Signed {',
    '  auth: Authorization,',
    '  signature: ByteArray,',
    '}',
    '',
    `pub const engine_vkey: ByteArray =\n  ${hex(bytesToHex(publicKeyFromSecret(ENGINE_TEST_SECRET)))}`,
    '',
    consts.join('\n\n'),
    '',
  ].join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL('vectors.test.ak', AIKEN_LIB), vectorsModule());
  writeFileSync(new URL('fixtures.ak', AIKEN_LIB), fixturesModule());
  console.log(`wrote vectors.test.ak and fixtures.ak (${fixtureCases().length} fixtures)`);
}
